name: Test, build and deploy
on: [push]
env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm ci
    # - name: Lint
    #   run: npm run lint
    # - name: Test
    #   run: npm run test
    # - name: Build
    #   run: npm run build
    - name: Deploy Package
      run: npx semantic-release